config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/', to: 'static_pages#home', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/:username', to: 'users#show', via: 'get' 
  match '/verify/:token', to: 'users#verify', via: 'get'
  match '/forgot' to: 'users#forgot', via: 'get'
  match '/reset/:token' to: 'users#reset', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Built By <a href="http://adamjsmith.info">Adam Smith</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class= "navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Twitter Clone", root_path, id: "logo" %>
				<div class="nav-collapse">
					<ul class="nav">
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "Help", help_path %></li>
						<% if signed_in? %>
							<li><%= link_to "Users", users_path %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Profile", current_user.username %></li>
									<li><%= link_to "Settings", edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li>
										<%= link_to "Sign out", signout_path, method: "delete" %>
									</li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Sign in", signin_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_not_home.html.erb
<div class="center hero-unit">
	<h1>Welcome to my Twitter Clone</h1>
	<h2> We are currently in development.</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= full_title(yield(:title)) %></title>
  		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
  		<meta name="viewport" content="width=device-width, initial scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>